### ISSUE TITLE
Foto-Finder Phases

### ISSUE THREAD

**Issue by whitneyfirth** [whitneyburton/wb-foto-finder#3]
### Architecture

Your entire application will consist of one HTML page or template.
You will have two javascript files:

1. [x] A `photo.js` file that contains a `Photo` class.
  * `Photo` methods must include, but are not limited to:
    1. [x] `constructor`
    2. [x] `saveToStorage`
    3. [x] `deleteFromStorage`
    4. [x] `updatePhoto`
2. [x] A `main.js` file that contains all dom related javascript.

### Data Model
* [x] An photo has an _id_, _title_, _caption_, _file_, and a _favorite_ property.
  * [x] The _id_ should be a unique identifier.
  * [x] _title_ and _caption_ are strings.
  * [x] _file_ is a URL string.
    * Use this [method](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) in order to convert a [blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) object into a URL.
  * [x] _favorite_ will be a boolean.

Each photo should be created as an instance of the `Photo` class.

#### Important Note:

For this project, you will need to open your application using a server.  You'll learn more about servers next mod, but for the purposes of this project, instead of doing `open index.html`, you will need to run `python -m SimpleHTTPServer` in your project directory.  Then go to `localhost:8000` and you should see your app there!

### Phase One: Building out the UI

This phase is all about setting up the user inputs and general structure of the page. The page will not be very interactive in this phase.

- [x] One input field at the top in order to search through photos
- [x] Two input fields for the `title` and `caption` of the photo
- [x] One input field to upload the photo (hint: look at the different HTML input element type attributes and how you can use one of them to select a file from your computer)
  -[This article](https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/) can help you with styling the file upload button
- [x] One "Add to Album" button for adding the photo to the album so you see it on the page
- [x] One `View Favorites` button to view all of your favorite photos.
- [x] A section for all of the photos in the album to live

### Phase Two: Implementing The Functionality

- [x] When a user fills in the Title, Caption, selects an image file, and then clicks the "Add to Album" button, the photo should be added to the photo album.
- [x] Each photo, when added to the album, is placed in a "card", and each photo card should display:
  -  [x] The photo
  - [x] The title of the photo
  - [x] The caption of the photo
  - [x] A button to mark the photo as a "Favorite" (counter on "View Favorites" button should reflect how many photos have been favorited)
  - [x] A button to "Remove" the photo from the album
- [x] Each photo card should persist (in `localStorage`) and should be present upon reloading the page.
  - [x] The photo should be added to `localStorage` using the `saveToStorage` method defined in the `Photo` class.
- [x] When a user clicks the title or caption of a photo in the list, that text should become an editable text field, pre-populated with the existing photo title or caption.
- [x] The user should be able to "commit" their changes by pressing "Enter/Return" or by clicking outside of the text field.
  - [x] This change should be saved in localStorage using the `updatePhoto` method defined in the `Photo` class.
  - [ ] Bonus: If the user clicks on the image, the user should be able to update the photo using the `updatePhoto` method.
- [x] When the user clicks on the "Favorite" button, the button should stay in the active (pink) state.  
  - [x] This favorited state should also persist after a page refresh using the `updatePhoto` method defined in the `Photo` class
- [x] When the user clicks on the "Trash" button, the photo should be removed from the page
  - [x] The photo should be removed from localStorage using the `deleteFromStorage` method defined in the `Photo` class.
- [x] The application should be responsive and work equally well on desktop and mobile

### Phase Three

Let's improve the user experience in this phase.

- [x] If the user does not have text in the Title **or** Caption input elements, **or** they have not selected a photo from the `photos` directory, then the "Add to Album" button should be disabled.
- [x] If there are no photos in the album yet, then there should be an indication to the user to add photos, displayed in the empty photo section.
- [x] The file selector should only allow image file types

#### Filtering and Searching by Text
We want the user to be able to search through all of their photos easily.

- [x] At the top of the page, include a text field labeled "Search".
- [x] As a user types in the search box, the list of photos should filter in real time to only display photos whose title or caption include the user's text. The page _should not_ reload.
- [x] Clearing the search box should restore all the photos to the list.
  - [x] Do not need to persist changes in between sessions.

#### Recent Photos

The application should only show the ten most recent Photos on page load.

* [ ] The application should contain a button labeled `Show more...`.
* [ ] When a user clicks on the `Show more...` button, the list should load all of the remaining photos.
* [ ] Once the remaining photos are loaded, the `Show more...` button should switch to a `Show less...` button.
* [ ] When a user clicks on the  `Show less...` button, the list should switch back to being the first 10 photos only.
  * [ ] This functionality should toggle back and forth based on that button click.
  * [ ] Do not need to persist changes in between sessions.

#### Viewing Favorites

Finally, let's let our user be able to view only their favorites.

- [x] The user should only see their favorites when they click on the `View Favorites` button. (consequently, the text on the button should then say `View All Photos`)
- [x] Clicking on the `View All Photos` button, the user should be able to see all of their photo cards.
- [x] When viewing favorites, search field should only search through the favorited photos.
  - [x] Do not need to persist changes in between sessions.
